[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
seven = "C9Pxggf14wNgFRefvkLi7CSGBdkTCBkn5Lxnfs9AuS1p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
